language: rust
rust:
    - stable
    - beta
    - nightly
script:
    - cargo build --verbose --all-features
    - cargo test --verbose --all-features
matrix:
    exclude:
        - rust: stable
        - rust: beta
