language: rust
rust:
    - stable
    - beta
    - nightly
env:
    - FEATURES=
script:
    - cargo build --verbose --features "$FEATURES"
    - cargo test --verbose --features "$FEATURES"
matrix:
    exclude:
        - rust: stable
          env: FEATURES= *
        - rust: beta
          env: FEATURES= *
